// GENERATED BY CodeGenerationUtility!!!
using DataModel;
using GraphQL.DataLoader;
using GraphQL.Types;

namespace GraphQLApi.Types
{
    /*
     * IMPORTANT - This class was generated by the CodeGenerationUtility.
     * To make a change edit the generation templates and run the tool
     * This must be done every time the models are updated,
     * or if the logic needs enhancing...
     */
    public sealed partial class DepartmentType : ObjectGraphType<Department>
    {
        public DepartmentType(QueryFactoryHelper queryFactoryHelper, IDataLoaderContextAccessor dataLoaderContextAccessor)
        {
            Name = "Department";

            Field(h => h.DepartmentId).Description("DepartmentId");

            Field(h => h.Name, true).Description("Name");



            ChildFields(queryFactoryHelper, dataLoaderContextAccessor);

        }
    }
}
